### ISSUE TITLE
Empty InputStream with status "Closed" when trying to download document, selfie or video from Onfido

### ISSUE THREAD

**Issue by andreabondi** [onfido/onfido-java#25]
Hi Team,

I'm trying to download a document with Java SDK, however I always receive an empty InputStream with status "Closed". I'm getting same behaviour with selfie and video download.

Below the snippet of code with what I'm doing.

```java
    public static void main(String[] args) {
        FileDownload download;
        try {
            download = downloadDocument("DOCUMENT_ID");
            InputStream document = download.content;
            byte[] buffer = new byte[document.available()];
            document.read(buffer);
            File targetFile = new File("temp.jpg");
            OutputStream outStream = new FileOutputStream(targetFile);
            outStream.write(buffer);
        } catch (Exception e) {
            e.printStackTrace();
        }
        System.out.println("Finished");
    }
​
    public static FileDownload downloadDocument(final String documentId) throws OnfidoException {
        final Onfido onfido = createOnfidoClient();
        return onfido.document.download(documentId);
    }
​
    private static Onfido createOnfidoClient() {
        return Onfido.builder()
                .apiToken("API_TOKEN")
                .build();
    }
```
This is the Stack Trace:
```
java.io.IOException: closed
	at okio.RealBufferedSource$inputStream$1.available(RealBufferedSource.kt:446)
	at com.company.Main.main(Main.java:19)
```

Thanks a lot for your help,
Best

Andrea

**Comment by crilofer** [comment]
Hi @andreabondi,

I am getting the same.

**Comment by crilofer** [comment]
should be solved with https://github.com/onfido/onfido-java/pull/26. Thanks @ciaran16

**Comment by andreabondi** [comment]
I just updated the version of the library and was able to successfully download a document image with the following code:
```java
            download = downloadDocument("<DOCUMENT_ID>");

            File targetFile = new File("temp.jpg");
            OutputStream outStream = new FileOutputStream(targetFile);

            outStream.write(download.content);
```
That's great, thanks!

Andrea
